// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:db834532-f21e-4bcf-9187-3e94add2bd3d',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'beerswithfriends-hosting-mobilehub-1162968537',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'do8lmiielev77.cloudfront.net',
aws_mobile_analytics_app_id : '98a0b30070cd4323874d727df002113d',
aws_project_id : '6cfc7b5d-8443-4f84-957c-cdacaee3dc15',
aws_project_name : 'beers-with-friends',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'beerswithfriends-mobilehub-1162968537',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});