// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_auth_facebook': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:db834532-f21e-4bcf-9187-3e94add2bd3d',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'beerswithfriends-hosting-mobilehub-1162968537',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'do8lmiielev77.cloudfront.net',
    'aws_facebook_app_id': '324425397966285',
    'aws_facebook_app_permissions': 'public_profile',
    'aws_mobile_analytics_app_id': '98a0b30070cd4323874d727df002113d',
    'aws_project_id': '6cfc7b5d-8443-4f84-957c-cdacaee3dc15',
    'aws_project_name': 'beers-with-friends',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'beerswithfriends-mobilehub-1162968537',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools_id': 'us-east-1_YKouu62W7',
    'aws_user_pools_web_client_id': '2omf58qubep8sac98kqdd28d4m',
}

export default awsmobile;
